Prioritize check for docker-compose.yml

diff --git a/docker_manage b/docker_manage
--- a/docker_manage
+++ b/docker_manage
@@ -36,6 +36,12 @@ VERSIONS_FILE_WITH_PATH="${STACK_FOLDER_WITH_PATH}/versions.txt"
 ### Preparation ####################################################################################
 ####################################################################################################
 
+# Look for Docker Compose file
+if [ ! -f "$COMPOSE_FILE_WITH_PATH" ]; then
+  echo -e "${RED}Cannot find Docker Compose File!${NC}"
+  exit 1
+fi
+
 # Detect Docker Compose command to be used
 if docker compose > /dev/null 2>&1; then
   COMPOSE_COMMAND="docker compose"
@@ -63,12 +69,6 @@ fi
 # Look for pv
 if ! command -v pv > /dev/null 2>&1; then
   echo -e "${RED}Cannot find pv (progress view)!${NC}"
-  exit 1
-fi
-
-# Look for Docker Compose file
-if [ ! -f "$COMPOSE_FILE_WITH_PATH" ]; then
-  echo -e "${RED}Cannot find Docker Compose File!${NC}"
   exit 1
 fi
 
